name: Continuous Integraiton
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  tagged-release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - name: Setup Node.js environment
        uses: actions/setup-node@latest
        with:
          registry-url: https://npm.pkg.github.com
      - name: Publish NPM Package
        run: npm publish
      - name: Create Relase
        uses: marvinpinto/action-automatic-releases@latest
        with:
          prerelease: false
          files: |
            *.json
