name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *.json
